// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Data;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ComputerContext))]
    [Migration("20230625061524_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsApi.Models.ComputerComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HDD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TdpCpu")
                        .HasColumnType("int");

                    b.Property<int>("TdpDefault")
                        .HasColumnType("int");

                    b.Property<int>("TdpGpu")
                        .HasColumnType("int");

                    b.Property<int>("TdpHDDNote")
                        .HasColumnType("int");

                    b.Property<int>("TdpHDDPC")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardATX")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardExtended")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardMicro")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardMini")
                        .HasColumnType("int");

                    b.Property<int>("TdpRamDual")
                        .HasColumnType("int");

                    b.Property<int>("TdpRamQuad")
                        .HasColumnType("int");

                    b.Property<int>("TdpRamSingles")
                        .HasColumnType("int");

                    b.Property<int>("TdpRamTri")
                        .HasColumnType("int");

                    b.Property<int>("TdpSSDNvme")
                        .HasColumnType("int");

                    b.Property<int>("TdpSSDSata")
                        .HasColumnType("int");

                    b.Property<int>("TdpTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComputerComponent");
                });
#pragma warning restore 612, 618
        }
    }
}
