// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Data;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ComputerContext))]
    [Migration("20230623021210_frist")]
    partial class frist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsApi.Models.ComputerComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HDD")
                        .HasColumnType("int");

                    b.Property<int>("Motherboard")
                        .HasColumnType("int");

                    b.Property<int>("QntRam")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RotuloCategory")
                        .HasColumnType("int");

                    b.Property<int>("SSD")
                        .HasColumnType("int");

                    b.Property<int>("TdpCpu")
                        .HasColumnType("int");

                    b.Property<int>("TdpGpu")
                        .HasColumnType("int");

                    b.Property<int>("TdpHDDNote")
                        .HasColumnType("int");

                    b.Property<int>("TdpHDDPC")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardATX")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardExtended")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardMicro")
                        .HasColumnType("int");

                    b.Property<int>("TdpMotherboardMini")
                        .HasColumnType("int");

                    b.Property<int>("TdpRam")
                        .HasColumnType("int");

                    b.Property<int>("TdpSSDNvme")
                        .HasColumnType("int");

                    b.Property<int>("TdpSSDSata")
                        .HasColumnType("int");

                    b.Property<int>("TdpTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComputerComponent");
                });
#pragma warning restore 612, 618
        }
    }
}
